### PR TITLE
Configure subdirectory doc

### PR DESCRIPTION
**Pull request by mkoeppe**
As a small step toward #1023.

`./configure --with-libparse && make && (cd doc && make)` leads to:
```
make: *** No rule to make target `cones.tex', needed by `singular.hlp'.  Stop.
```

### CODE REVIEW

**Comment by mkoeppe** [comment]
OK, got a bit farther:
```
**** Error: while running example bracket from plural.doc:1610.
Call: '../Singular/Singular  -teqr12345678 --no-rc ./examples/bracket.sing > ./examples/bracket.res'
make: *** [plural.tex] Error 1
```

**Comment by mkoeppe** [comment]
Using `make -k`, there are some additional errors.

```$ make -C doc -k
perl ./doc2tex.pl -docdir ./d2t_singular -Singular ../Singular/Singular -verbose 1  -make /Library/Developer/CommandLineTools/usr/bin/make -exdir ./examples -exclude polymake -o letterplace.tex letterplace.doc
(d2t letterplace.doc==>letterplace.tex<Examples_of_use_of_@sc{Letterplace}><Example_of_use_of_@sc{Letterplace}_over_Z><Example_of_use_of_@sc{Letterplace}_over_Z_1>(Example_of_use_of_@sc{Letterplace}_over_Z_2)
**** Error: while running example Example_of_use_of_@sc{Letterplace}_over_Z_2 from letterplace.doc:173.
Call: '../Singular/Singular  -teqr12345678 --no-rc ./examples/Example_of_use_of_@sc{Letterplace}_over_Z_2.sing > ./examples/Example_of_use_of_@sc{Letterplace}_over_Z_2.res'
make: *** [letterplace.tex] Error 1
perl ./doc2tex.pl -docdir ./d2t_singular -Singular ../Singular/Singular -verbose 1  -make /Library/Developer/CommandLineTools/usr/bin/make -exdir ./examples -exclude polymake -o plulibs.tex plulibs.doc
(d2t plulibs.doc==>plulibs.tex<lib bimodules ><lib bfun ><lib central ><lib dmod ><lib dmodapp ><lib dmodideal ><lib dmodvar ><lib involut ><lib gkdim ><lib ncalg ><lib ncdecomp ><lib ncfactor (d2t d2t_singular/ncfactor_lib.doc==>d2t_singular/ncfactor_lib.tex<ncfactor><facWeyl>(facFirstWeyl)
**** Error: while running example facFirstWeyl from d2t_singular/ncfactor_lib.doc:192.
Call: '../Singular/Singular  -teqr12345678 --no-rc ./examples/facFirstWeyl.sing > ./examples/facFirstWeyl.res'
make[1]: *** [d2t_singular/ncfactor_lib.tex] Error 1

**** Error: non-zero exit status of system call: '/Library/Developer/CommandLineTools/usr/bin/make  --no-print-directory -s  VERBOSE=1 ./d2t_singular/ncfactor_lib.tex': Inappropriate ioctl for device
make: *** [plulibs.tex] Error 1
perl ./doc2tex.pl -docdir ./d2t_singular -Singular ../Singular/Singular -verbose 1  -make /Library/Developer/CommandLineTools/usr/bin/make -exdir ./examples -exclude polymake -o pyobject.tex pyobject.doc
(d2t pyobject.doc==>pyobject.tex<pyobject><pyobject_declarations><pyobject_expressions><pyobject_operations>(pyobject_related_functions)
**** Error: while running example pyobject_related_functions from pyobject.doc:212.
Call: '../Singular/Singular  -teqr12345678 --no-rc ./examples/pyobject_related_functions.sing > ./examples/pyobject_related_functions.res'
make: *** [pyobject.tex] Error 1
make: *** No rule to make target `INSTALL_unix.texi', needed by `singular.tex'.
make: *** No rule to make target `README_download.texi', needed by `singular.tex'.
make: *** No rule to make target `README_ftp.texi', needed by `singular.tex'.
make: *** No rule to make target `README_distribution.texi', needed by `singular.tex'.
make: *** No rule to make target `README_src.texi', needed by `singular.tex'.
make: *** No rule to make target `INSTALL_win.texi', needed by `singular.tex'.
make: Target `all' not remade because of errors.
```

**Comment by hannes14** [comment]
README_src.texi etc. removed

**Comment by mkoeppe** [comment]
> README_src.texi etc. removed

Thanks!

**Comment by mkoeppe** [comment]
Getting much further now, but getting stuck here:
```
**** Error: while running example absFactorizeBCG from d2t_singular/absfact_lib.doc:163.
Call: '../Singular/Singular  -teqr12345678 --no-rc ./examples/absFactorizeBCG.sing > ./examples/absFactorizeBCG.res'
make[1]: *** [d2t_singular/absfact_lib.tex] Error 1

**** Error: non-zero exit status of system call: '/Library/Developer/CommandLineTools/usr/bin/make  --no-print-directory -s  VERBOSE=1 ./d2t_singular/absfact_lib.tex': 
make: *** [singular.tex] Error 1
make: Target `all' not remade because of errors.
(base) egret:~/s/sage/singular-sources (configure_doc %)$ cat doc/examples/absFactorizeBCG.res
./examples/absFactorizeBCG.sing   1> LIB "absfact.lib";
./examples/absFactorizeBCG.sing   2> ring R = (0), (x,y), lp;
./examples/absFactorizeBCG.sing   3> poly p = (-7*x^2 + 2*x*y^2 + 6*x + y^4 + 14*y^2 + 47)*(5x2+y2)^3*(x-y)^4;
./examples/absFactorizeBCG.sing   4> def S = absFactorizeBCG(p) ;
   ? (extended) system("absFact",...) not implemented
   ? error occurred in or before absfact.lib::absFactorizeBCG line 765: `  list tmpf=system ("absFact", p);`
   ? leaving absfact.lib::absFactorizeBCG (740)
   skipping text from ` ` error at token `)`
./examples/absFactorizeBCG.sing   5> setring(S);
   ? S is no name of a ring/qring
   ? error occurred in or before ./examples/absFactorizeBCG.sing line 5: `setring(S);`
./examples/absFactorizeBCG.sing   6> absolute_factors;
   ? `absolute_factors` is undefined
   ? error occurred in or before ./examples/absFactorizeBCG.sing line 6: `absolute_factors;`
STDIN   1> $
```

**Comment by hannes14** [comment]
Am Wed, Mar 10, 2021 at 11:48:32AM -0800 schrieb Matthias Köppe:
>  ./examples/absFactorizeBCG.sing   4> def S = absFactorizeBCG(p) ;
>     ? (extended) system("absFact",...) not implemented
Then this Singular is build without NTL AND without FLINT - at least one
of them is needed for some functionality.
see Singular/extra.cc, line 1013

**Comment by mkoeppe** [comment]
Thanks, I'll try with a new build

**Comment by mkoeppe** [comment]
Also, during `make -C doc` here on macOS, I am getting multiple notifications "Do you want the application “Singular” to accept incoming network connections?"

**Comment by mkoeppe** [comment]
Something also automatically opens the webpage https://www.singular.uni-kl.de/Manual/4-2-0/ in my browser as a side effect

**Comment by mkoeppe** [comment]
A new build with NTL and FLINT, and with installed 4ti2 and normaliz...
Now stuck at this example.
```
$ cat doc/examples/RiemannRochBN.res
./examples/RiemannRochBN.sing   1> LIB "brillnoether.lib";
   skipping text from `;`
   ? unknown type `cone`
   ? error occurred in or before divisors.lib::mod_init line 78: `newstruct("pdivisor","list summands, cone tail");`
   ? leaving divisors.lib::mod_init (75)
```
What happened to "cone"?

**Comment by mkoeppe** [comment]
After working around an issue with using `gfanlib` (#1061), here's the next error:
```
$ cat doc/examples/parallelWaitFirst.res
./examples/parallelWaitFirst.sing   1> LIB "parallel.lib";
./examples/parallelWaitFirst.sing   2> ring R = 0, (x,y,z), lp;
// ** Could not find dynamic library: p_Procs_FieldIndep.so (path )
// ** Singular will work properly, but much slower.
// ** See the INSTALL section in the Singular manual for details.
./examples/parallelWaitFirst.sing   3> ideal I = 3x3y+x3+xy3+y2z2, 2x3z-xy-xz3-y4-z2, 2x2yz-2xy2+xz2-y4;
./examples/parallelWaitFirst.sing   4> ideal J = x10+x9y2, x2y7-y8;
./examples/parallelWaitFirst.sing   5> list commands = list("std", "std");
./examples/parallelWaitFirst.sing   6> list arguments = list(list(I), list(J));
./examples/parallelWaitFirst.sing   7> parallelWaitFirst(commands, arguments);
Singular(63619,0x109b84dc0) malloc: *** error for object 0x7fda11808a00: pointer being freed was not allocated
Singular(63619,0x109b84dc0) malloc: *** set a breakpoint in malloc_error_break to debug
Singular : signal 6 (v: 4201):
current line:>>;return();<<
Segment fault/Bus error occurred (r:12345678)
please inform the authors
```

**Comment by hannes14** [comment]
Am Wed, Mar 10, 2021 at 03:41:44PM -0800 schrieb Matthias Köppe:
>    Also, during make -C doc here on macOS, I am getting multiple
>    notifications "Do you want the application “Singular” to accept incoming
>    network connections?"
Yes, parallel algorithms start several Singular and communicate via TCP
ports  - mainly on localhost - one should trust localhost.

**Comment by hannes14** [comment]
Am Wed, Mar 10, 2021 at 03:50:42PM -0800 schrieb Matthias Köppe:
>    Something also automatically opens the webpage
>    https://www.singular.uni-kl.de/Manual/4-2-0/ in my browser as a side
>    effect
The command help resp. ? opens a browser as a last resort - but the
example for help is not executed while building the manual and I do not
know any other place in the manual which calls help.

**Comment by hannes14** [comment]
Am Wed, Mar 10, 2021 at 05:42:21PM -0800 schrieb Matthias Köppe:
>     ? unknown type `cone`
divisors.lib loads polymake.lib, which loads gfanlib.so, which creates cone, fan and polytope

**Comment by hannes14** [comment]
>  Singular(63619,0x109b84dc0) malloc: *** error for object 0x7fda11808a00: pointer being freed was not allocated
>  Singular(63619,0x109b84dc0) malloc: *** set a breakpoint in malloc_error_break to debug
Could not reproduce: valgrind on linux reports no errors, works on OsX,
does not work on Cygwin (but no crash).

**Comment by mkoeppe** [comment]
> Singular(63619,0x109b84dc0) malloc: *** error for object 0x7fda11808a00: pointer being freed was not allocated Singular(63619,0x109b84dc0) malloc: *** set a breakpoint in malloc_error_break to debug
> Could not reproduce: valgrind on linux reports no errors, works on OsX, does not work on Cygwin (but no crash).

For the record, this one was on macOS Catalina, built with `./configure --with-libparse --with-ntl=$SAGE_LOCAL --with-gmp=/nofunnystuff --disable-pyobject-module && make clean && make -j20 GMP_LIBS="-lgmp" CDDGMPLDFLAGS="-lcddgmp -lgmp"`within a Sage 9.3.beta8 shell

Right now I cannot reproduce it either; it's possible that this happens only if one clicks "Deny" on "Do you want the application “Singular” to accept incoming network connections?"`

**Comment by mkoeppe** [comment]
Next failure:
```
$ cat doc/examples/getWitnessSet.res
./examples/getWitnessSet.sing   1> LIB "recover.lib";
./examples/getWitnessSet.sing   2> //First, we write the input file for bertini, then run bertini
./examples/getWitnessSet.sing   3. ring r=0,(x,y,z),dp;
// ** Could not find dynamic library: p_Procs_FieldIndep.so (path )
// ** Singular will work properly, but much slower.
// ** See the INSTALL section in the Singular manual for details.
./examples/getWitnessSet.sing   4> ideal I=(x-y)*(y-z)*(x-z);
./examples/getWitnessSet.sing   5> writeBertiniInput(I,40);
./examples/getWitnessSet.sing   6> system("sh","bertini input");
sh: bertini: command not found
32512
./examples/getWitnessSet.sing   7> //Then we change the ring and extract the witness set from main_data
./examples/getWitnessSet.sing   8. ring R=(complex,40,i),(x,y,z),dp;
./examples/getWitnessSet.sing   9> list P=getWitnessSet();
   ? open: Error for link _ of type: ASCII, mode: , name: main_data
   ? cannot read from `main_data`
   ? error occurred in or before recover.lib::getWitnessSet line 1081: `   r=read("main_data");`
   ? leaving recover.lib::getWitnessSet (0)
   skipping text from `;` error at token `)`
./examples/getWitnessSet.sing  10> P;
empty list
STDIN   1> $
```

Should this be made conditional on the presence of an installation of `bertini`?

**Comment by mkoeppe** [comment]
> Am Wed, Mar 10, 2021 at 05:42:21PM -0800 schrieb Matthias Köppe:
> ? unknown type `cone`
> divisors.lib loads polymake.lib, which loads gfanlib.so, which creates cone, fan and polytope

OK wow, for this PR I have disabled it.

**Comment by mkoeppe** [comment]
Another segfault:
```
$ cat doc/examples/T1.res 
./examples/T1.sing   1> LIB "stanleyreisner.lib";
./examples/T1.sing   2> ring R=0,(x(1..4)),lp;
// ** Could not find dynamic library: p_Procs_FieldIndep.so (path )
// ** Singular will work properly, but much slower.
// ** See the INSTALL section in the Singular manual for details.
./examples/T1.sing   3> ideal i=x(1),x(2),x(3),x(4),x(1)*x(4),x(2)*x(4),x(1)*x(3),x(2)*x(3);
./examples/T1.sing   4> list L=T1(i);
Singular(8167,0x11971ddc0) malloc: *** error for object 0x7f9ee5e06740: pointer being freed was not allocated
Singular(8167,0x11971ddc0) malloc: *** set a breakpoint in malloc_error_break to debug
Singular : signal 6 (v: 4201):
current line:>>  intmat V=fgp(I,a,b);<<
Segment fault/Bus error occurred (r:12345678)
please inform the authors
trying to restart...
```

**Comment by mkoeppe** [comment]
This version builds the documentation for me on macOS without error.

For the record:
```
$ ./config.status --config
'--with-libparse' '--with-ntl=/Users/mkoeppe/s/sage/sage-rebasing/worktree-algebraic-2018-spring/local' '--with-gmp=/nofunnystuff' '--disable-pyobject-module' 'CC=gcc' 'LDFLAGS=-L/Users/mkoeppe/s/sage/sage-rebasing/worktree-algebraic-2018-spring/local/lib -Wl,-rpath,/Users/mkoeppe/s/sage/sage-rebasing/worktree-algebraic-2018-spring/local/lib ' 'CXX=g++ -std=gnu++11' '--enable-omalloc' 'OMALLOC_LIBS=/Users/mkoeppe/s/sage/singular-sources/omalloc/libomalloc.la' 'OMALLOC_INCLUDES=-I/Users/mkoeppe/s/sage/singular-sources' '--with-Singular' 'RESOURCES_LIBS=/Users/mkoeppe/s/sage/singular-sources/resources/libsingular_resources.la' 'RESOURCES_INCLUDES=-I/Users/mkoeppe/s/sage/singular-sources ' 'FACTORY_LIBS=/Users/mkoeppe/s/sage/singular-sources/factory/libfactory.la' 'FACTORY_INCLUDES=-I/Users/mkoeppe/s/sage/singular-sources -I/Users/mkoeppe/s/sage/singular-sources/factory -I/Users/mkoeppe/s/sage/singular-sources/factory/include'  OMALLOC_LIBS='/Users/mkoeppe/s/sage/singular-sources/omalloc/libomalloc.la' OMALLOC_INCLUDES='-I/Users/mkoeppe/s/sage/singular-sources' --with-Singular RESOURCES_LIBS='/Users/mkoeppe/s/sage/singular-sources/resources/libsingular_resources.la' RESOURCES_INCLUDES='-I/Users/mkoeppe/s/sage/singular-sources ' FACTORY_LIBS='/Users/mkoeppe/s/sage/singular-sources/factory/libfactory.la' FACTORY_INCLUDES='-I/Users/mkoeppe/s/sage/singular-sources -I/Users/mkoeppe/s/sage/singular-sources/factory -I/Users/mkoeppe/s/sage/singular-sources/factory/include'
```

**Comment by mkoeppe** [comment]
Ready for review.

**Pull request merged**
