### PR TITLE
doc: Add missing `tag:normaliz`, fix quoting bug, update Sage CI (macOS arm64 testing)

### PR DESCRIPTION
**Pull request by mkoeppe**
To fix this build failure seen in https://github.com/Singular/Singular/actions/runs/7557525633/job/20577033209#step:11:4703
```
  [singular-git]   ><lib sagbiNormaliz make[5]: *** No rule to make target 'd2t_singular/sagbiNormaliz_lib.tex'.
  [singular-git]   
  [singular-git]   **** Error: non-zero exit status of system call: 'make -f Makefile-docbuild  --no-print-directory -s  VERBOSE=1 ./d2t_singular/sagbiNormaliz_lib.tex': Inappropriate ioctl for device
  [singular-git]   make[4]: *** [Makefile-docbuild:173: singular.tex] Error 1
  [singular-git]   sed -e "s/BR_PLURAL_BR/(plural)/g" <plural.tex >s-plural.tex
  [singular-git]   sed -e "s/BR_PLURAL_BR/(plural)/g" <plulibs.tex >s-plulibs.tex
  [singular-git]   sed -e "s/BR_LETTERPLACE_BR/(letterplace)/g" <letterplace.tex >s-letterplace.tex
  [singular-git]   make[4]: Target 'singular.info' not remade because of errors.
  [singular-git]   make[3]: *** [Makefile:630: singular.info] Error 2
  [singular-git]   ********************************************************************************
```

### CODE REVIEW

**Comment by mkoeppe** [comment]
@hannes14 This change by itself does not fix the build failure; what am I missing?

**Comment by hannes14** [comment]
normaliz.lib (and probably sagbiNormaliz.lib) need features introduced in normaliz 3.10.0.
Debian 12 (for example) has normaliz 3.9.
Is your normaliz too old?

**Comment by hannes14** [comment]
or https://github.com/Singular/Singular/commit/b15c1cfe67ca2bc259900269cce8aaeb069fc1d3 is missing

**Comment by mkoeppe** [comment]
This error shows up in a build of Singular without normaliz.

**Comment by mkoeppe** [comment]
> or [b15c1cf](https://github.com/Singular/Singular/commit/b15c1cfe67ca2bc259900269cce8aaeb069fc1d3) is missing

OK, I've rebased to latest spielwiese, and now it seems to work.

**Comment by mkoeppe** [comment]
Now that it gets farther, I see the following failures on about half of the tested platforms:
https://github.com/Singular/Singular/actions/runs/7840627819/job/21396068454?pr=1205#step:14:2827
```
  unset DISPLAY SINGULAR_EXECUTABLE && SINGULARPATH="$(for d in ../Singular/dyn_modules/*/.libs; do printf $d:; done)" PATH="../IntegerProgramming:$PATH" perl ./doc2tex.pl -docdir ./d2t_singular -Singular ../Singular/Singular -verbose 1  -make "make -f Makefile-docbuild" -exdir ./examples -exclude qepcad -exclude lrcalc -exclude normaliz -exclude topcom -exclude pyobject -exclude bertini  -exclude crash -o countedref.tex countedref.doc
  (d2t countedref.doc==>countedref.tex(reference_and_shared__experimental_../Singular/Singular: line 150: ls: command not found
  ../Singular/Singular: line 150: ls: command not found
  )(reference_and_shared__experimental__1../Singular/Singular: line 150: ls: command not found
  )(reference_and_shared__experimental__2../Singular/Singular: line 150: ls: command not found
  )(reference_and_shared__experimental__3../Singular/Singular: line 150: ls: command not found
  )(reference_declarations../Singular/Singular: line 150: ls: command not found
  )(reference_expressions../Singular/Singular: line 150: ls: command not found
  )(shared_declarations../Singular/Singular: line 150: ls: command not found
  )(shared_expressions../Singular/Singular: line 150: ls: command not found
  )(reference_and_shared_operations../Singular/Singular: line 150: ls: command not found
  )(reference_and_shared_operations_1../Singular/Singular: line 150: ls: command not found
  )(reference_and_shared_operations_2../Singular/Singular: line 150: ls: command not found
  )(reference_and_shared_related_functions../Singular/Singular: line 150: ls: command not found
  )(reference_and_shared_related_functions_1../Singular/Singular: line 150: ls: command not found
  )(reference_and_shared_related_functions_2../Singular/Singular: line 150: ls: command not found
  )==>countedref.tex)
```

**Comment by mkoeppe** [comment]
OK, this fixed the docbuild for many platforms.

**Comment by mkoeppe** [comment]
On [docker / linux (ubuntu-bionic-gcc_8, standard)](https://github.com/Singular/Singular/actions/runs/7853642966/job/21433797799?pr=1205#logs)
https://github.com/Singular/Singular/actions/runs/7853642966/job/21433797799?pr=1205#step:11:6045
```
  [singular-git]   unset DISPLAY SINGULAR_EXECUTABLE && SINGULARPATH="$(for d in ../Singular/dyn_modules/*/.libs; do printf $d:; done)" PATH="../IntegerProgramming:$PATH" perl ./doc2tex.pl -docdir ./d2t_singular -Singular ../Singular/Singular -verbose 1  -make "make -f Makefile-docbuild" -exdir ./examples -exclude qepcad -exclude lrcalc -exclude normaliz -exclude topcom -exclude pyobject -exclude bertini  -exclude crash -o letterplace.tex letterplace.doc
  [singular-git]   (d2t letterplace.doc==>letterplace.tex(Examples_of_use_of_@sc{Letterplace})Unescaped left brace in regex is illegal here in regex; marked by <-- HERE in m/^./examples/Examples_of_use_of_@sc{ <-- HERE Letterplace}.sing\s*([0-9]+)../ at ./doc2tex.pl line 400, <RES> line 1.
  [singular-git]   Makefile-docbuild:180: recipe for target 'letterplace.tex' failed
  [singular-git]   make[4]: *** [letterplace.tex] Error 25
```

Edit: Fixed by https://github.com/Singular/Singular/commit/ce021493acdc6628babc8fe3d1200d5096a9607f

**Comment by mkoeppe** [comment]
On [docker / linux (almalinux-9-python3.11, standard)](https://github.com/Singular/Singular/actions/runs/7853642966/job/21433802724?pr=1205#logs)
https://github.com/Singular/Singular/actions/runs/7853642966/job/21433802724?pr=1205#step:11:3863
```
  [singular-git]   /bin/sh '/sage/local/var/tmp/sage/build/singular-git/src/build-aux/missing' makeinfo --force --no-split singular.tex
  [singular-git]   /sage/local/var/tmp/sage/build/singular-git/src/build-aux/missing: line 81: makeinfo: command not found
```

Likewise on [docker / linux (archlinux-latest, minimal)](https://github.com/Singular/Singular/actions/runs/7853642966/job/21433803051?pr=1205#logs)

Edit: Fixed by e1bfa95

**Comment by mkoeppe** [comment]
Build hangs on [docker / linux (opensuse-tumbleweed-python3.10, minimal)](https://github.com/Singular/Singular/actions/runs/7853642966/job/21433803681?pr=1205#logs)
failed 3 hours ago in 6h 0m 16s
https://github.com/Singular/Singular/actions/runs/7853642966/job/21433803681?pr=1205#step:11:3844
```
  [singular-git]   unset DISPLAY SINGULAR_EXECUTABLE && SINGULARPATH="$(for d in ../Singular/dyn_modules/*/.libs; do printf $d:; done)" PATH="../IntegerProgramming:$PATH" perl ./doc2tex.pl -docdir ./d2t_singular -Singular ../Singular/Singular -verbose 1  -make "make -f Makefile-docbuild" -exdir ./examples -exclude qepcad -exclude lrcalc -exclude normaliz -exclude gfan -exclude topcom -exclude pyobject -exclude bertini  -exclude crash -o general.tex general.doc
Sat, 10 Feb 2024 15:57:18 GMT
  [singular-git]   (d2t general.doc==>general.tex(Command_line_options)(Quotient_rings)(Term_orderings)(Function_without_return_value)(Print_command)(Names)(Names_1)(Names_2)(Names_3)(Objects)(Type_casting)(How_to_use_links)(How_to_use_links_1)(ASCII_links)(Ssi_linksmake[4]: *** Deleting file 'general.tex'
Sat, 10 Feb 2024 15:57:18 GMT
  [singular-git]   make[4]: *** [Makefile-docbuild:180: general.tex] Terminated
```

**Comment by mkoeppe** [comment]
Build also hangs on [macos / local-macos (latest, homebrew-macos-usrlocal-minimal)](https://github.com/Singular/Singular/actions/runs/7853642966/job/21433797176?pr=1205#logs)
https://github.com/Singular/Singular/actions/runs/7853642966/job/21433797176?pr=1205

**Comment by hannes14** [comment]
Seems that perl at these system does snot like @sc in headings, 
ce021493acdc6628babc8fe3d1200d5096a9607f changes that.
But that is the difference of these system w.r.t. all the others?

**Comment by mkoeppe** [comment]
Rebased over latest spielwiese

**Comment by mkoeppe** [comment]
Each of the tested platforms brings some version of Perl. We don't test the specifics in the Sage configuration script

**Comment by mkoeppe** [comment]
> Seems that perl at these system does snot like @sc in headings,
> [ce02149](https://github.com/Singular/Singular/commit/ce021493acdc6628babc8fe3d1200d5096a9607f) changes that.

Thanks, that helped.

Still open: The hanging builds as reported

**Comment by hannes14** [comment]
All the remaining failing tests mention "macOs". Omitting the VSPACE interprocess communication may help:
https://github.com/Singular/Singular/commit/cd08f3e3253ab5f83a88042c54606fd8b38c5ed9
(it helps on a M1-macos, which sometimes hang during the test, not sure about linux docker systems inside macOs)

**Comment by mkoeppe** [comment]
> All the remaining failing tests mention "macOs". Omitting the VSPACE interprocess communication may help:
> [cd08f3e](https://github.com/Singular/Singular/commit/cd08f3e3253ab5f83a88042c54606fd8b38c5ed9)
> (it helps on a M1-macos, which sometimes hang during the test, not sure about linux docker systems inside macOs)

For the record, all macOS tests here are on x86_64 and do not involve Docker.

And the hangs mentioned here: https://github.com/Singular/Singular/pull/1205#issuecomment-1937104875 do not involve macOS. They are openSUSE

Rebased on latest spielwiese and waiting for updated tests now

**Comment by mkoeppe** [comment]
I put in a timelimit and made the build verbose to make it more visible what is hanging. On macOS:
```
[singular-git] unset DISPLAY SINGULAR_EXECUTABLE && SINGULARPATH="$(for d in ../Singular/dyn_modules/*/.libs; do printf $d:; done)" PATH="../IntegerProgramming:$PATH" perl ./doc2tex.pl -docdir ./d2t_singular -Singular ../Singular/Singular -verbose 1  -make "make -f Makefile-docbuild" -exdir ./examples -exclude qepcad -exclude lrcalc -exclude normaliz -exclude gfan -exclude topcom -exclude pyobject -exclude bertini  -exclude crash -o decodegb.tex decodegb.doc
[singular-git] (d2t decodegb.doc==>decodegb.tex==>decodegb.tex)
[singular-git] unset DISPLAY SINGULAR_EXECUTABLE && SINGULARPATH="$(for d in ../Singular/dyn_modules/*/.libs; do printf $d:; done)" PATH="../IntegerProgramming:$PATH" perl ./doc2tex.pl -docdir ./d2t_singular -Singular ../Singular/Singular -verbose 1  -make "make -f Makefile-docbuild" -exdir ./examples -exclude qepcad -exclude lrcalc -exclude normaliz -exclude gfan -exclude topcom -exclude pyobject -exclude bertini  -exclude crash -o examples.tex examples.doc
[singular-git] (d2t examples.doc==>examples.tex(Basic_programming)(Writing_procedures_and_libraries)(Rings_associated_to_monomial_orderings)(Long_coefficients)(Parameters)(Formatting_output)(Parallelization_with_ssi_links)(Dynamic_modules)(groebner_and_std)(Groebner_basis_conversion)(slim_Groebner_bases)(Saturation)(Finite_fields)(Elimination)(Free_resolution)(Handling_graded_modules)(Computation_of_Ext)(Depth)(Factorization)(Primary_decomposition)(Normalization)(Kernel_of_module_homomorphisms)(Algebraic_dependence)(Milnor_and_Tjurina_number)(Critical_points)(Polar_curves)(T1_and_T2)(Deformations)(Invariants_of_plane_curve_singularities)(Branches_of_space_curve_singularities)(Resolution_of_singularities)(G_a_-Invariants)(Invariants_of_a_finite_group)(Left_and_two-sided_Groebner_bases)(Right_Groebner_bases_and_syzygies)(Solving_systems_of_polynomial_equations)(AG_codes)==>examples.tex)
[singular-git] unset DISPLAY SINGULAR_EXECUTABLE && SINGULARPATH="$(for d in ../Singular/dyn_modules/*/.libs; do printf $d:; done)" PATH="../IntegerProgramming:$PATH" perl ./doc2tex.pl -docdir ./d2t_singular -Singular ../Singular/Singular -verbose 1  -make "make -f Makefile-docbuild" -exdir ./examples -exclude qepcad -exclude lrcalc -exclude normaliz -exclude gfan -exclude topcom -exclude pyobject -exclude bertini  -exclude crash -o general.tex general.doc
make: *** [singular] Terminated: 15
make[2]: *** [singular-SAGE_LOCAL-no-deps] Terminated: 15
[singular-git] (d2t general.doc==>general.tex(Command_line_options)(Quotient_rings)(Term_orderings)(Function_without_return_value)(Print_command)(Names)(Names_1)(Names_2)(Names_3)(Objects)(Type_casting)(ASCII_links)(Ssi_linksmake[4]: *** Deleting file `general.tex'
[singular-git] make[4]: *** [general.tex] Terminated: 15
make[1]: *** [/Users/runner/work/Singular/Singular/.tox/local-homebrew-macos-usrlocal-standard/local/var/lib/sage/installed/singular-git] Terminated: 15
[singular-git] make[3]: *** [singular.info] Terminated: 15
```
(https://github.com/Singular/Singular/actions/runs/7896994588/job/21552239487?pr=1205#step:10:9097)

**Comment by hannes14** [comment]
Thanks for the verbose output: the example with problems is the example from the section "Ssi links" which
starts Singular as a Server waiting a some port - it needs connections to/from localhost at some free port >1025.
If there is no such free port, it aborts with an error - but if connection are blocked, it waits indefinitly.
956c8a3cd124c9c2699cd7c5eb20233d90e2f41a disables testing this example.
Together with the other changes of today it should work now.

**Comment by mkoeppe** [comment]
Thanks! This gets us one step farther.
Next failure on macOS:
```
[singular-git] ><lib sagbigrob (d2t d2t_singular/sagbigrob_lib.doc==>d2t_singular/sagbigrob_lib.tex(LTGS)(SGNF)(SPOLY)(SGB)==>d2t_singular/sagbigrob_lib.tex)
[singular-git] ><lib sagbiNormaliz (d2t d2t_singular/sagbiNormaliz_lib.doc==>d2t_singular/sagbiNormaliz_lib.tex{sagbiGeneral}{sagbiByDegree}{sagbiHilbControlled}==>d2t_singular/sagbiNormaliz_lib.tex)
[singular-git] ><lib stanleyreisner (d2t d2t_singular/stanleyreisner_lib.doc==>d2t_singular/stanleyreisner_lib.tex(T1)
[singular-git] **** Error: while running example T1 from d2t_singular/stanleyreisner_lib.doc:60.
[singular-git] Call: '../Singular/Singular  -teqr12345678 --no-rc ./examples/T1.sing > ./examples/T1.res'
[singular-git] make[5]: *** [d2t_singular/stanleyreisner_lib.tex] Error 1
[singular-git] 
[singular-git] **** Error: non-zero exit status of system call: 'make -f Makefile-docbuild  --no-print-directory -s  VERBOSE=1 ./d2t_singular/stanleyreisner_lib.tex': Inappropriate ioctl for device
[singular-git] make[4]: *** [singular.tex] Error 1
[singular-git] sed -e "s/BR_PLURAL_BR/(plural)/g" <plural.tex >s-plural.tex
[singular-git] sed -e "s/BR_PLURAL_BR/(plural)/g" <plulibs.tex >s-plulibs.tex
[singular-git] sed -e "s/BR_LETTERPLACE_BR/(letterplace)/g" <letterplace.tex >s-letterplace.tex
[singular-git] make[4]: Target `singular.info' not remade because of errors.
[singular-git] make[3]: *** [singular.info] Error 2
```
https://github.com/Singular/Singular/actions/runs/7904829521/job/21577012664?pr=1205#step:10:8674

**Comment by mkoeppe** [comment]
on `opensuse-tumbleweed`:
```
[singular-git] ><lib involut (d2t d2t_singular/involut_lib.doc==>d2t_singular/involut_lib.tex(findInvo)(findInvoDiag)(findAuto)(ncdetection)(involution)(isInvolution)(isAntiEndo)==>d2t_singular/involut_lib.tex)
[singular-git] ><lib gkdim (d2t d2t_singular/gkdim_lib.doc==>d2t_singular/gkdim_lib.tex(GKdim)==>d2t_singular/gkdim_lib.tex)
[singular-git] ><lib ncalg (d2t d2t_singular/ncalg_lib.doc==>d2t_singular/ncalg_lib.tex(makeUsl2)(makeUsl)(makeUgl)(makeUso5)(makeUso6)(makeUso7)(makeUso8)(makeUso9)(makeUso10)(makeUso11)(makeUso12)(makeUsp1)(makeUsp2)(makeUsp3)(makeUsp4)(makeUsp5)(makeUg2)(makeUf4)(makeUe6)(makeUe7)(makeUe8)(makeQso3)(makeQsl2)(makeQsl3)(Qso3Casimir)(GKZsystem)
[singular-git] **** Error: while running example GKZsystem from d2t_singular/ncalg_lib.doc:996.
[singular-git] Call: '../Singular/Singular  -teqr12345678 --no-rc ./examples/GKZsystem.sing > ./examples/GKZsystem.res'
[singular-git] make[5]: *** [Makefile-docbuild:180: d2t_singular/ncalg_lib.tex] Error 1
[singular-git] 
[singular-git] **** Error: non-zero exit status of system call: 'make -f Makefile-docbuild  --no-print-directory -s  VERBOSE=1 ./d2t_singular/ncalg_lib.tex': Inappropriate ioctl for device
[singular-git] make[4]: *** [Makefile-docbuild:180: plulibs.tex] Error 1
[singular-git] unset DISPLAY SINGULAR_EXECUTABLE && SINGULARPATH="$(for d in ../Singular/dyn_modules/*/.libs; do printf $d:; done)" PATH="../IntegerProgramming:$PATH" perl ./doc2tex.pl -docdir ./d2t_singular -Singular ../Singular/Singular -verbose 1  -make "make -f Makefile-docbuild" -exdir ./examples -exclude qepcad -exclude lrcalc -exclude normaliz -exclude gfan -exclude topcom -exclude pyobject -exclude bertini  -exclude crash -o sca.tex sca.doc
[singular-git] (d2t sca.doc==>sca.tex(Graded_commutative_algebras__SCA_)==>sca.tex)
[singular-git] unset DISPLAY SINGULAR_EXECUTABLE && SINGULARPATH="$(for d in ../Singular/dyn_modules/*/.libs; do printf $d:; done)" PATH="../IntegerProgramming:$PATH" perl ./doc2tex.pl -docdir ./d2t_singular -Singular ../Singular/Singular -verbose 1  -make "make -f Makefile-docbuild" -exdir ./examples -exclude qepcad -exclude lrcalc -exclude normaliz -exclude gfan -exclude topcom -exclude pyobject -exclude bertini  -exclude crash -o pyobject.tex pyobject.doc
[singular-git] (d2t pyobject.doc==>pyobject.tex(pyobject)(pyobject_declarations)(pyobject_expressions)(pyobject_operations)(pyobject_related_functions)(pyobject_related_functions_1)(python_eval)(python_import)(python_run)==>pyobject.tex)
[singular-git] sed -e "s/BR_PLURAL_BR/(plural)/g" <plural.tex >s-plural.tex
[singular-git] sed -e "s/BR_LETTERPLACE_BR/(letterplace)/g" <letterplace.tex >s-letterplace.tex
[singular-git] make[4]: Target 'singular.info' not remade because of errors.
```
https://github.com/Singular/Singular/actions/runs/7904829521/job/21577034497?pr=1205#step:11:6614

Edit: Fixed in 15a2fc4

**Comment by mkoeppe** [comment]
on `ubuntu-jammy-standard`:
```
[singular-git] ><lib maxlike (d2t d2t_singular/maxlike_lib.doc==>d2t_singular/maxlike_lib.tex(likeIdeal)(logHessian)(getMaxPoints)(maxPoints)(maxPointsProb)==>d2t_singular/maxlike_lib.tex)
[singular-git] ><lib modfinduni (d2t d2t_singular/modfinduni_lib.doc==>d2t_singular/modfinduni_lib.tex==>d2t_singular/modfinduni_lib.tex)
[singular-git] ><lib modwalk (d2t d2t_singular/modwalk_lib.doc==>d2t_singular/modwalk_lib.tex(modWalk)(modrWalk)(modfWalk)
[singular-git] **** Error: while running example modfWalk from d2t_singular/modwalk_lib.doc:163.
[singular-git] Call: '../Singular/Singular  -teqr12345678 --no-rc ./examples/modfWalk.sing > ./examples/modfWalk.res'
[singular-git] make[5]: *** [Makefile-docbuild:180: d2t_singular/modwalk_lib.tex] Error 1
[singular-git] 
[singular-git] **** Error: non-zero exit status of system call: 'make -f Makefile-docbuild  --no-print-directory -s  VERBOSE=1 ./d2t_singular/modwalk_lib.tex': Inappropriate ioctl for device
[singular-git] make[4]: *** [Makefile-docbuild:173: singular.tex] Error 1
[singular-git] sed -e "s/BR_PLURAL_BR/(plural)/g" <plural.tex >s-plural.tex
[singular-git] sed -e "s/BR_PLURAL_BR/(plural)/g" <plulibs.tex >s-plulibs.tex
[singular-git] sed -e "s/BR_LETTERPLACE_BR/(letterplace)/g" <letterplace.tex >s-letterplace.tex
[singular-git] make[4]: Target 'singular.info' not remade because of errors.
[singular-git] make[3]: *** [Makefile:630: singular.info] Error 2
```
https://github.com/Singular/Singular/actions/runs/7904829521/job/21577017228?pr=1205#step:11:8284


Edit: Fixed as of 2d5d7e969

**Comment by mkoeppe** [comment]
on `debian-sid-standard` hanging:
```
[singular-git] ><lib matrix (d2t d2t_singular/matrix_lib.doc==>d2t_singular/matrix_lib.tex(compress)(concat)(diag)(dsum)(flatten)(genericmat)(is_complex)(outer)(power)(skewmat)(submat)(symmat)(unitmat)(gauss_col)(gauss_row)(addcol)(addrow)(multcol)(multrow)(permcol)(permrow)(rowred)(colred)(linear_relations)(rm_unitrow)(rm_unitcol)(headStand)(symmetricBasis)(exteriorBasis)(symmetricPower)(exteriorPower)==>d2t_singular/matrix_lib.tex)
[singular-git] ><lib linalg (d2t d2t_singular/linalg_lib.doc==>d2t_singular/linalg_lib.tex(inverse)(inverse_B)(inverse_L)(sym_gauss)(orthogonalize)(diag_test)(busadj)(charpoly)(adjoint)(det_B)(gaussred)(gaussred_pivot)(gauss_nf)(mat_rk)(U_D_O)(pos_def)(hessenberg)(eigenvals)(minipoly)(spnf)(spprint)(jordan)(jordanbasis)(jordanmatrix)(jordannf)==>d2t_singular/linalg_lib.tex)
[singular-git] ><lib absfact (d2t d2t_singular/absfact_lib.doc==>d2t_singular/absfact_lib.tex(absFactorize)(absFactorizeBCG)==>d2t_singular/absfact_lib.tex)
[singular-git] ><lib algebra (d2t d2t_singular/algebra_lib.doc==>d2t_singular/algebra_lib.tex(algebra_containment)(module_containment)(inSubring)(algDependent)(alg_kernel)(is_injective)(is_surjective)(is_bijective)(noetherNormal)(mapIsFinite)(finitenessTest)(nonZeroEntry)==>d2t_singular/algebra_lib.tex)
make: *** [Makefile:40: singular] Terminated
Terminated
```
https://github.com/Singular/Singular/actions/runs/7904829521/job/21577021051?pr=1205#step:11:6489

Edit: Fixed as of 2d5d7e969

**Comment by hannes14** [comment]
https://github.com/Singular/Singular/commit/2d5d7e969be169286decf139f1ba0d2d47c38dba and before fixes a bug for stanleyreisner.lib which produces crashes on macos.
For the other (GKZsystem from ncalglib): toric_ideal (from IntegerProgramming/toric_ideal.cc) has to be in the PATH

**Comment by mkoeppe** [comment]
The failure on opensuse-tumbleweed-minimal is some strange library problem
```
><lib gkdim (d2t d2t_singular/gkdim_lib.doc==>d2t_singular/gkdim_lib.tex(GKdim)==>d2t_singular/gkdim_lib.tex)
><lib ncalg (d2t d2t_singular/ncalg_lib.doc==>d2t_singular/ncalg_lib.tex(makeUsl2)(makeUsl)(makeUgl)(makeUso5)(makeUso6)(makeUso7)(makeUso8)(makeUso9)(makeUso10)(makeUso11)(makeUso12)(makeUsp1)(makeUsp2)(makeUsp3)(makeUsp4)(makeUsp5)(makeUg2)(makeUf4)(makeUe6)(makeUe7)(makeUe8)(makeQso3)(makeQsl2)(makeQsl3)(Qso3Casimir)(GKZsystem)::group::./examples/GKZsystem.sing   1> LIB "ncalg.lib";
./examples/GKZsystem.sing   2> // example 3.1.4 from the [SST] without the vector w
./examples/GKZsystem.sing   3. intmat A[2][4]=3,2,1,0,0,1,2,3;
./examples/GKZsystem.sing   4> print(A);
     3     2     1     0
     0     1     2     3
./examples/GKZsystem.sing   5> def D1 = GKZsystem(A,"lp","ect");
sh: /sage/local/lib/libreadline.so.8: no version information available (required by sh)
sh: /sage/local/lib/libreadline.so.8: no version information available (required by sh)
sh: /sage/local/lib/libreadline.so.8: no version information available (required by sh)
sh: /sage/local/lib/libreadline.so.8: no version information available (required by sh)
sh: symbol lookup error: sh: undefined symbol: rl_set_timeout, version READLINE_8.2
   ? toric_ideal failed with error code 32512
   ? leaving toric.lib::toric_ideal_1 (0)
   ? leaving toric.lib::toric_ideal (704)
   ? leaving ncalg.lib::GKZsystem (606)
./examples/GKZsystem.sing   6> setring D1;
   ? D1 is no name of a ring/qring
   ? error occurred in or before ./examples/GKZsystem.sing line 6: `setring D1;`
./examples/GKZsystem.sing   7> D1;
`D1`
./examples/GKZsystem.sing   8> print(GKZid);
`GKZid`
./examples/GKZsystem.sing   9> // now, consider A with the vector w=1,1,1,1
./examples/GKZsystem.sing  10. intvec v=1,1,1,1;
./examples/GKZsystem.sing  11> def D2 = GKZsystem(A,"lp","blr",v);
sh: /sage/local/lib/libreadline.so.8: no version information available (required by sh)
sh: /sage/local/lib/libreadline.so.8: no version information available (required by sh)
sh: /sage/local/lib/libreadline.so.8: no version information available (required by sh)
sh: /sage/local/lib/libreadline.so.8: no version information available (required by sh)
sh: symbol lookup error: sh: undefined symbol: rl_set_timeout, version READLINE_8.2
   ? toric_ideal failed with error code 32512
   ? leaving toric.lib::toric_ideal_2 (0)
   ? leaving toric.lib::toric_ideal (708)
   ? leaving ncalg.lib::GKZsystem (612)
./examples/GKZsystem.sing  12> setring D2;
   ? D2 is no name of a ring/qring
   ? error occurred in or before ./examples/GKZsystem.sing line 12: `setring D2;`
./examples/GKZsystem.sing  13> print(GKZid);
`GKZid`
STDIN   1> $

**** Error: while running example GKZsystem from d2t_singular/ncalg_lib.doc:996.
Call: '../Singular/Singular  -teqr12345678 --no-rc ./examples/GKZsystem.sing > ./examples/GKZsystem.res'
make[5]: *** [Makefile-docbuild:180: d2t_singular/ncalg_lib.tex] Error 1

**** Error: non-zero exit status of system call: 'make -f Makefile-docbuild  --no-print-directory -s  VERBOSE=1 ./d2t_singular/ncalg_lib.tex': Inappropriate ioctl for device
```
(https://github.com/Singular/Singular/actions/runs/8060393602/job/22016967991?pr=1205#step:14:9643)

Edit: Fixed in [15a2fc4](https://github.com/Singular/Singular/pull/1205/commits/15a2fc4aaec3839a6e9c4e54914f1b9a55fd645e)

**Comment by mkoeppe** [comment]
Hang on [linux (fedora-30, standard)](https://github.com/Singular/Singular/actions/runs/8076645951/job/22066083210?pr=1205)
```
  [singular-git] ><lib algebra Unescaped left brace in regex is deprecated here (and will be fatal in Perl 5.30), passed through in regex; marked by <-- HERE in m/([^\@]|^)\@(code|math|xref|pxref|ref){ <-- HERE (.*?)}/ at ./pl2doc.pl line 295.
Wed, 28 Feb 2024 09:57:20 GMT
  [singular-git] (d2t d2t_singular/algebra_lib.doc==>d2t_singular/algebra_lib.tex(algebra_containment)(module_containment)(inSubring)(algDependent)(alg_kernel)(is_injective)(is_surjective)(is_bijective)(noetherNormal)(mapIsFinite)(finitenessTest)(nonZeroEntry)==>d2t_singular/algebra_lib.tex)
Wed, 28 Feb 2024 09:57:20 GMT
  [singular-git] ><lib assprimeszerodim Unescaped left brace in regex is deprecated here (and will be fatal in Perl 5.30), passed through in regex; marked by <-- HERE in m/([^\@]|^)\@(code|math|xref|pxref|ref){ <-- HERE (.*?)}/ at ./pl2doc.pl line 295.
Wed, 28 Feb 2024 09:57:20 GMT
  make: *** [Makefile:40: singular] Terminated
Wed, 28 Feb 2024 09:57:20 GMT
  make[2]: *** [Makefile:3390: singular-SAGE_LOCAL-no-deps] Terminated
Wed, 28 Feb 2024 09:57:20 GMT
```

Same hang on [docker / linux (linuxmint-20.3, minimal)](https://github.com/Singular/Singular/actions/runs/8076645951/job/22066081897?pr=1205#logs)
```
  [singular-git] ><lib linalg (d2t d2t_singular/linalg_lib.doc==>d2t_singular/linalg_lib.tex(inverse)(inverse_B)(inverse_L)(sym_gauss)(orthogonalize)(diag_test)(busadj)(charpoly)(adjoint)(det_B)(gaussred)(gaussred_pivot)(gauss_nf)(mat_rk)(U_D_O)(pos_def)(hessenberg)(eigenvals)(minipoly)(spnf)(spprint)(jordan)(jordanbasis)(jordanmatrix)(jordannf)==>d2t_singular/linalg_lib.tex)
  [singular-git] ><lib absfact (d2t d2t_singular/absfact_lib.doc==>d2t_singular/absfact_lib.tex(absFactorize)(absFactorizeBCG)==>d2t_singular/absfact_lib.tex)
  [singular-git] ><lib algebra (d2t d2t_singular/algebra_lib.doc==>d2t_singular/algebra_lib.tex(algebra_containment)(module_containment)(inSubring)(algDependent)(alg_kernel)(is_injective)(is_surjective)(is_bijective)(noetherNormal)(mapIsFinite)(finitenessTest)(nonZeroEntry)==>d2t_singular/algebra_lib.tex)
  make: *** [Makefile:40: singular] Terminated
  Terminated
  The command '/bin/sh -c make SAGE_SPKG="sage-spkg -y -o" ${USE_MAKEFLAGS} ${TARGETS}' returned a non-zero code: 143
```

**Comment by hannes14** [comment]
escape left brace:  https://github.com/Singular/Singular/commit/d967b408f6917fff1643b60658321472d0124f58

**Comment by mkoeppe** [comment]
Thanks @hannes14, the "unescaped brace" warnings are gone now. But the hangs remain. They appear to be random, not specific to one of these systems. In this run the hang showed up on a different platform: [docker / linux (linuxmint-20.2, standard)](https://github.com/Singular/Singular/actions/runs/8099970255/job/22137938121?pr=1205#logs)

```
  [singular-git] ><lib linalg (d2t d2t_singular/linalg_lib.doc==>d2t_singular/linalg_lib.tex(inverse)(inverse_B)(inverse_L)(sym_gauss)(orthogonalize)(diag_test)(busadj)(charpoly)(adjoint)(det_B)(gaussred)(gaussred_pivot)(gauss_nf)(mat_rk)(U_D_O)(pos_def)(hessenberg)(eigenvals)(minipoly)(spnf)(spprint)(jordan)(jordanbasis)(jordanmatrix)(jordannf)==>d2t_singular/linalg_lib.tex)
  [singular-git] ><lib absfact (d2t d2t_singular/absfact_lib.doc==>d2t_singular/absfact_lib.tex(absFactorize)(absFactorizeBCG)==>d2t_singular/absfact_lib.tex)
  [singular-git] ><lib algebra (d2t d2t_singular/algebra_lib.doc==>d2t_singular/algebra_lib.tex(algebra_containment)(module_containment)(inSubring)(algDependent)(alg_kernel)(is_injective)(is_surjective)(is_bijective)(noetherNormal)(mapIsFinite)(finitenessTest)(nonZeroEntry)==>d2t_singular/algebra_lib.tex)
  make: *** [Makefile:40: singular] Terminated
  Terminated
```

**Comment by mkoeppe** [comment]
Also another likely random failure in `parallel_lib.doc`:
```
[singular-git] ><lib modular (d2t d2t_singular/modular_lib.doc==>d2t_singular/modular_lib.tex(modular)==>d2t_singular/modular_lib.tex)
[singular-git] ><lib parallel (d2t d2t_singular/parallel_lib.doc==>d2t_singular/parallel_lib.tex(parallelWaitN)(parallelWaitFirst)
[singular-git] **** Error: while running example parallelWaitFirst from d2t_singular/parallel_lib.doc:113.
[singular-git] Call: '../Singular/Singular  -teqr12345678 --no-rc ./examples/parallelWaitFirst.sing > ./examples/parallelWaitFirst.res'
[singular-git] make[5]: *** [d2t_singular/parallel_lib.tex] Error 1
[singular-git] 
[singular-git] **** Error: non-zero exit status of system call: 'make -f Makefile-docbuild  --no-print-directory -s  VERBOSE=1 
```
[macos / local-macos (13, xcode_15.0, homebrew-macos-usrlocal-standard)](https://github.com/Singular/Singular/actions/runs/8099970255/job/22137929405?pr=1205#logs)

**Pull request merged**
