### PR TITLE
vdim for letterplace

### PR DESCRIPTION
**Pull request by kabouzeid**
`vdim` aka `lpKDim` implementiert in `kernel/combinatorics/hdegree.cc`

einige Methoden in den LIBs umbenannt, da nicht mehr benötigt.

### CODE REVIEW

**Comment by hannes14** [comment]
tests fail: Tst/Manual/lpGkDim.diff       Tst/Manual/lpKDim.diff
Tst/Manual/lpGlDimBound.diff  Tst/Manual/lpSickleDim.diff
Tst/Manual/lpKDimCheck.diff

**Comment by kabouzeid** [comment]
Is expected behavior, forgot about them. Will fix.

**Comment by kabouzeid** [comment]
Tests should pass now. They failed because of the renamed library methods.

**Comment by hannes14** [comment]
merge manually

**Pull request closed without merging**
