### PR TITLE
Add portability testing and continuous integration using Sage

### PR DESCRIPTION
**Pull request by mkoeppe**

### CODE REVIEW

**Comment by fingolfin** [comment]
Note: I started working on PR #1019 on July 3, so it is not a reaction to this PR (in fact I only saw this PR just now :-). The two PRs complement each other.

The advantage of "my" PR is that a CI run takes 10-15 minutes to complete, while for this PR here, CI runs are more like 8 hours.

**Comment by mkoeppe** [comment]
Great. The more CI, the merrier. And indeed, they complement each other. Your continuous testing run on #1019 is suitable to run on every commit. The continuous integration workflow on this PR is configured to run only on tags and pull requests. I would hope that the Singular project will find it valuable when preparing new releases, or making major configuration changes. I'll be happy to help with making necessary adjustments or explaining details.

**Comment by mkoeppe** [comment]
A run with the updated workflow can be seen at https://github.com/mkoeppe/Sources/actions/runs/181585170

**Comment by mkoeppe** [comment]
Thanks for merging this. I'll send you a follow-up PR that will reflect recent changes in Sage

**Pull request merged**
